# pip3 install boto3 pycryptodome
import boto3

from Crypto.Cipher import PKCS1_OAEP
from Crypto.PublicKey import RSA

KMS_KEY = "604a3562-e32f-42bd-9089-48c5f451e14f"
kms_client = boto3.client("kms", region_name="eu-central-1")

def generate_key_pair():
    keys = kms_client.generate_data_key_pair_without_plaintext(KeyId=KMS_KEY, KeyPairSpec="RSA_2048")

#    print("KEYS ", keys)

    # keys["PrivateKeyCiphertextBlob"] is the cyphered private key
    # keys["PublicKey"] is the public key
    return keys["PublicKey"], keys["PrivateKeyCiphertextBlob"]

def encrypt_data(data, public_key):
    # Import an RSA key (public or private).
    public_key = RSA.import_key(public_key)
    #Return a cipher object PKCS1OAEP_Cipher
    # that can be used to perform PKCS#1 OAEP encryption or decryption.
    cipher = PKCS1_OAEP.new(public_key)
    # Encodes the string, using the specified encoding.
    encoded_data = data.encode("utf-8")
    # Encrypt a message with PKCS#1 OAEP.
    return cipher.encrypt(encoded_data)

def decrypt_data(data, private_key):
    # Import an RSA key (public or private).
    private_key = RSA.import_key(private_key)
    #Return a cipher object PKCS1OAEP_Cipher
    # that can be used to perform PKCS#1 OAEP encryption or decryption.
    cipher = PKCS1_OAEP.new(private_key)
    # Encrypt a message with PKCS#1 OAEP.
    decrypted_data = cipher.decrypt(data)
    # Decodes the bytes-like object using the specified encoding.
    return decrypted_data.decode("utf-8")


def main():
    public_key, cyphered_private_key = generate_key_pair()
    decrypt_response = kms_client.decrypt(CiphertextBlob=cyphered_private_key)

#     print("DECRYPT RESPONSE ", decrypt_response)

    private_key = decrypt_response["Plaintext"]   # This is the private key in plain text

    # Simple example of encrypting and decrypting data from a string
    # using the public and private keys generated by the KMS
    data = "Hello World"
    encrypted_data = encrypt_data(data, public_key)
    decrypted_data = decrypt_data(encrypted_data, private_key)
    print(decrypted_data)

    # Simple example of encrypting and decrypting data from a text file
    # using an intermediate file to store the encrypted data and
    # using the public and private keys generated by the KMS
    file = open("original_data.txt", "r")
    data = file.read()
    print("Original data: ", data)
    file.close()

    encrypted_data = encrypt_data(data, public_key)
    file = open("encrypted_data.txt", "wb")
    file.write(encrypted_data)
    file.close()

    file = open("encrypted_data.txt", "rb")
    encrypted_data = file.read()
    file.close()
    print("Encrypted data: ", encrypted_data)
    decrypted_data = decrypt_data(encrypted_data, private_key)
    print("Decrypted data: ", decrypted_data)

    file = open("decrypted_data.txt", "w")
    file.write(decrypted_data)
    file.close()

if __name__ == "__main__":
    main()